### ISSUE TITLE
Playbook for phpMyAdmin does not set up correct permission on configuration file for Red Hat based builds.

### ISSUE THREAD

**Issue by madamowicz** [rackspace-orchestration-templates/ansible-roles#12]
Hi Guys,

I have recently found out that Ansible playbook does not set up correct permission for /etc/phpMyAdmin directory and configuration file inside. It happens only on Red Hat based builds.

`# cd /etc/phpMyAdmin
# ls -la

total 24
drwxr-x---.   2 root apache  4096 Sep 16 12:38 .
drwxr-xr-x. 106 root root   12288 Sep 16 12:15 ..
-rw-r-----.   1 root apache  5520 Sep 16 10:11 config.inc.php
`

I have tested this with Rackspace Orchestration templates for PHP and Wordpress stacks.

Cheers,
Marcin Adamowicz

**Comment by madamowicz** [comment]
New pull request's awaiting for this issue.

**Comment by chrishultin** [comment]
Thanks for the fix!  I've merged the changes in and pushed them out for all future builds.
